# tasks file for rolesdemo
- name: Enable nginx
  shell: "amazon-linux-extras enable nginx1.12"
  become: yes

- name: Install nginx
  yum:
    name: nginx
    state: latest
  become: yes

- name: Copy html files
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: /var/www/html/index.html
    mode: 0644
  become: yes

- name: Copy cars files
  copy:
    src: "{{ role_path }}/files/cars.jpg"
    dest: /var/www/html/cars.jpg
    mode: 0644
  become: yes

- name: Copy nginx files
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644
  become: yes
  notify: Restart Nginx

- name: Copy nginx files
  copy:
    src: "{{ role_path }}/files/default.conf"
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  become: yes
  notify: Restart Nginx
