    - name: Ansible loop with index example
      debug:
        msg: "echo loop index at {{ item.0 }} and value at {{item.1}}"
      with_indexed_items:
        - "hello1"
        - "hello2"
        - "hello3"

    - name: Ansible loop with conditional example
      debug:
        msg: "{{ item }}"
      with_items:
        - "hello2"
        - "hello-1"
        - "hello3"
      when: item == "{{ loop_1 }}"