    - debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_architecture }})"
    
    - name: Ansible bases distributions task
      debug:
        msg: "{{ item }}"
      with_items:
        - "hello1"
        - "hello2"
        - "hello3"
      when: ansible_distribution == "Amazon"